# kubernetes/backend-service.yaml
# --- Service pour le Backend Flask ---
# Expose le déploiement Backend pour qu'il soit accessible
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:

    app: backend
  ports:
    - name: http 
      protocol: TCP
      port: 5000
      targetPort: 5000
      # nodePort: 30005 # Si type=NodePort, spécifie un port fixe (optionnel, entre 30000-32767)
  # --- Type de Service ---
  # NodePort expose le service sur un port statique sur l'IP de chaque nœud du cluster.
  # Utile pour les tests locaux ou si tu n'as pas d'Ingress/LoadBalancer.
  type: NodePort
