apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: frontend

        image: ghcr.io/alyspn/ma-bibliotheque/frontend:main
        imagePullPolicy: Always
        ports:
        - containerPort: 80

        livenessProbe: # Vérifie si le conteneur est "vivant"
          httpGet:
            # Vérifie si Nginx sert bien le fichier principal
            path: /index.html
            port: 80
          initialDelaySeconds: 5 # Attendre 5s après démarrage
          periodSeconds: 10 # Vérifier toutes les 10s
        readinessProbe: # Vérifie si le conteneur est prêt à recevoir du trafic
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 5 # Attendre 5s après démarrage
          periodSeconds: 10 # Vérifier toutes les 10s
