# kubernetes/postgres-secret.yaml
# --- Secret pour PostgreSQL ---
# Contient les informations sensibles (identifiants) encodées en Base64.
apiVersion: v1
kind: Secret
metadata:
  # Nom du secret, qui sera référencé par les déploiements
  name: postgres-secret
type: Opaque # Type de secret générique
data:
  # Valeurs encodées en Base64 pour:
  # POSTGRES_USER: user_bibliotheque
  # POSTGRES_PASSWORD: password_secret
  # POSTGRES_DB: bibliotheque_db
  POSTGRES_USER: dXNlcl9iaWJsaW90aGVxdWU=
  POSTGRES_PASSWORD: cGFzc3dvcmRfc2VjcmV0
  POSTGRES_DB: YmlibGlvdGhlcXVlX2Ri
