# .github/workflows/ci.yml

name: CI Pipeline - Application Bibliothèque

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with Flake8
        working-directory: ./backend
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # Tests optionnels ici

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # --- Modification ici ---
      - name: Build and Load Backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false
          tags: my-bibliotheque-backend:ci
          # Charger l'image dans le démon Docker local pour les étapes suivantes
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # --- Modification ici ---
      - name: Build and Load Frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false
          tags: my-bibliotheque-frontend:ci
          # Charger l'image dans le démon Docker local pour les étapes suivantes
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Scan Backend image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          # Référence à l'image chargée localement
          image-ref: 'my-bibliotheque-backend:ci'
          format: 'table'
          exit-code: '0' # Ne pas faire échouer si vulnérabilités trouvées (pour l'instant)
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Scan Frontend image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          # Référence à l'image chargée localement
          image-ref: 'my-bibliotheque-frontend:ci'
          format: 'table'
          exit-code: '0' # Ne pas faire échouer si vulnérabilités trouvées (pour l'instant)
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
